
import javax.swing.*;import javax.swing.table.*;import java.awt.*;import java.util.Date;import java.util.concurrent.TimeUnit;
public class UserUI {
    public static void showUserDashboard(VehicleRentalSystem app,Component parent){
        JFrame f=new JFrame("User - "+app.currentUser.name);f.setSize(1000,600);f.setLocationRelativeTo(parent);
        JPanel root=new JPanel(new BorderLayout(12,12));
        JLabel header=new JLabel("<html><h2 style='margin:0'>KLH Vehicle Rentals</h2><small>Book vehicles by choosing start & end date/time</small></html>");
        header.setBorder(BorderFactory.createEmptyBorder(8,8,8,8));root.add(header,BorderLayout.NORTH);
        DefaultTableModel vm=new DefaultTableModel(new String[]{"ID","Name","Type","Rate (₹/day)"},0);for(Vehicle v:app.vehicles.values())vm.addRow(new Object[]{v.id,v.name,v.type,app.df.format(v.ratePerDay)});
        JTable vt=new JTable(vm);vt.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);JScrollPane leftScroll=new JScrollPane(vt);leftScroll.setPreferredSize(new Dimension(420,400));root.add(leftScroll,BorderLayout.WEST);
        JPanel form=new JPanel();form.setLayout(new BoxLayout(form,BoxLayout.Y_AXIS));form.setBorder(BorderFactory.createTitledBorder("Book Vehicle"));
        JPanel fldRow=new JPanel(new FlowLayout(FlowLayout.LEFT));fldRow.add(new JLabel("Vehicle ID:"));JTextField tfVid=new JTextField(12);tfVid.setEditable(false);fldRow.add(tfVid);JButton btnSelect=new JButton("Select from table");fldRow.add(btnSelect);form.add(fldRow);
        fldRow=new JPanel(new FlowLayout(FlowLayout.LEFT));fldRow.add(new JLabel("Start (date & time):"));SpinnerDateModel startModel=new SpinnerDateModel(new Date(),null,null,java.util.Calendar.MINUTE);JSpinner spStart=new JSpinner(startModel);spStart.setEditor(new JSpinner.DateEditor(spStart,"dd-MM-yyyy HH:mm"));fldRow.add(spStart);
        fldRow.add(new JLabel("End (date & time):"));SpinnerDateModel endModel=new SpinnerDateModel(new Date(System.currentTimeMillis()+3600*1000),null,null,java.util.Calendar.MINUTE);JSpinner spEnd=new JSpinner(endModel);spEnd.setEditor(new JSpinner.DateEditor(spEnd,"dd-MM-yyyy HH:mm"));fldRow.add(spEnd);form.add(fldRow);
        fldRow=new JPanel(new FlowLayout(FlowLayout.LEFT));JLabel calculated=new JLabel("Duration: 0 days, 0 hours (auto)");fldRow.add(calculated);form.add(fldRow);
        fldRow=new JPanel(new FlowLayout(FlowLayout.LEFT));fldRow.add(new JLabel("Extra hours (optional):"));JSpinner spExtra=new JSpinner(new SpinnerNumberModel(0,0,24,1));fldRow.add(spExtra);form.add(fldRow);
        fldRow=new JPanel(new FlowLayout(FlowLayout.LEFT));fldRow.add(new JLabel("Payment:"));JComboBox<String> cbPayment=new JComboBox<>(new String[]{"Cash","UPI","Card"});fldRow.add(cbPayment);form.add(fldRow);
        JPanel btnRow=new JPanel(new FlowLayout(FlowLayout.LEFT));JButton btnPreviewCost=new JButton("Preview Cost");JButton btnBook=new JButton("Book (request)");JButton btnGenerate=new JButton("Generate Invoice");btnGenerate.setEnabled(false);JButton btnMain=new JButton("Return to Main Menu");
        btnRow.add(btnPreviewCost);btnRow.add(btnBook);btnRow.add(btnGenerate);btnRow.add(btnMain);form.add(btnRow);
        root.add(form,BorderLayout.CENTER);
        DefaultTableModel bm=new DefaultTableModel(new String[]{"BookingID","Vehicle","ReqOn","Days","Hours","Status","Amount (₹)"},0);JTable bt=new JTable(bm);refreshUserBookingsTable(app,bm);JScrollPane rightScroll=new JScrollPane(bt);rightScroll.setPreferredSize(new Dimension(420,400));root.add(rightScroll,BorderLayout.EAST);
        btnSelect.addActionListener(ev->{int r=vt.getSelectedRow(); if(r>=0) tfVid.setText((String)vt.getValueAt(r,0));});
        Runnable computeDuration=()->{Date start=(Date)spStart.getValue();Date end=(Date)spEnd.getValue(); if(end.before(start)){calculated.setText("End before start! Please correct."); return;} long diffMs=end.getTime()-start.getTime(); long totalHours=TimeUnit.MILLISECONDS.toHours(diffMs); long days=totalHours/24; long hours=totalHours%24; calculated.setText(String.format("Duration: %d days, %d hours (auto)", days, hours));};
        spStart.addChangeListener(e->computeDuration.run()); spEnd.addChangeListener(e->computeDuration.run());
        btnPreviewCost.addActionListener(ev->{ try{ String vid=tfVid.getText().trim(); if(vid.isEmpty()){JOptionPane.showMessageDialog(f,"Select vehicle first."); return;} Vehicle v=app.vehicles.get(vid); if(v==null){JOptionPane.showMessageDialog(f,"Vehicle not found."); return;} Date start=(Date)spStart.getValue(); Date end=(Date)spEnd.getValue(); if(end.before(start)){JOptionPane.showMessageDialog(f,"End < start."); return;} long diffMs=end.getTime()-start.getTime(); long totalHours=TimeUnit.MILLISECONDS.toHours(diffMs); long days=totalHours/24; long hours=totalHours%24; int extra=(Integer)spExtra.getValue(); double amount=days*v.ratePerDay+(hours+extra)*(v.ratePerDay/24.0); String rupee="\u20B9 "; JOptionPane.showMessageDialog(f,"Estimated amount: "+rupee+app.df.format(amount)); }catch(Exception ex){JOptionPane.showMessageDialog(f,ex.getMessage());}});
        btnBook.addActionListener(ev->{ try{ String vid=tfVid.getText().trim(); if(vid.isEmpty()){JOptionPane.showMessageDialog(f,"Select vehicle first."); return;} Vehicle v=app.vehicles.get(vid); if(v==null){JOptionPane.showMessageDialog(f,"Vehicle not found."); return;} Date start=(Date)spStart.getValue(); Date end=(Date)spEnd.getValue(); if(end.before(start)){JOptionPane.showMessageDialog(f,"End < start."); return;} long diffMs=end.getTime()-start.getTime(); long totalHours=TimeUnit.MILLISECONDS.toHours(diffMs); int days=(int)(totalHours/24); int hours=(int)(totalHours%24); int extra=(Integer)spExtra.getValue(); double amount=days*v.ratePerDay+(hours+extra)*(v.ratePerDay/24.0); Booking b=new Booking(app.generateId("BKG"),app.currentUser.email,vid,new Date(),days,hours+extra,amount,(String)cbPayment.getSelectedItem()); app.bookings.put(b.bookingId,b); app.saveBookings(); JOptionPane.showMessageDialog(f,"Booking requested. Admin approval required."); refreshUserBookingsTable(app,bm); }catch(Exception ex){JOptionPane.showMessageDialog(f,ex.getMessage()); }});
        bt.getSelectionModel().addListSelectionListener(evt->{ int r=bt.getSelectedRow(); if(r<0){ btnGenerate.setEnabled(false); return;} String bid=(String)bt.getValueAt(r,0); Booking sel=app.bookings.get(bid); btnGenerate.setEnabled(sel!=null && sel.status==BookingStatus.APPROVED); });
        btnGenerate.addActionListener(ev->{ int r=bt.getSelectedRow(); if(r<0){ JOptionPane.showMessageDialog(f,"Select an approved booking first."); return;} String bid=(String)bt.getValueAt(r,0); Booking sel=app.bookings.get(bid); if(sel==null || sel.status!=BookingStatus.APPROVED){ JOptionPane.showMessageDialog(f,"Selected booking is not approved."); return;} try{ InvoiceGenerator.generate(sel,app,f); }catch(Exception ex){ JOptionPane.showMessageDialog(f,ex.getMessage()); }});
        btnMain.addActionListener(ev->{ f.dispose(); app.buildUI(); });
        f.setContentPane(root); f.setVisible(true);
    }
    private static void refreshUserBookingsTable(VehicleRentalSystem app, DefaultTableModel bm){ bm.setRowCount(0); for(Booking b: app.bookings.values()){ if(b.userEmail.equals(app.currentUser.email)){ bm.addRow(new Object[]{b.bookingId,b.vehicleId,app.formatDate(b.requestedOn),b.days,b.hours,b.status,app.df.format(b.amount)}); } } }
}
